theme: jekyll-theme-architect
title: [NOVA Democrats]
description: [Democrats of Northern Virginia Community College]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
